/**
 * Created by Piotr Kucia on 10.07.2018.
 */

public with sharing class A18_VFC_AssetController {

    public void addAsset(Asset__c assetRecord){

    }

    public void updateAsset(Asset__c assetRecord){

    }

    public void deleteAsset(ID assetId){

    }

    public void getAssets(String searchPhrase, String status){

    }

    public List<A18_DTO_AssetStatus> getAssetStatuses(){

        //temporarily
        return NULL;

    }

}