/**
 * Created by Piotr Kucia on 10.07.2018.
 */

public with sharing class A18_AC_AssetUserController {

    public void assignAssetToUser(ID assetId, ID userId){

    }

    public void updateAssetToUser(ID assetToUserId, ID assetId, ID userId){

    }

    public void removeAssetToUser(ID assetToUserId){

    }

    public List<A18_DTO_AssetUser> getAssetToUserList(){

        //temporarily
        return NULL;

    }

}