/**
 * Created by Piotr Kucia on 10.07.2018.
 */

public with sharing class A18_VFC_AssetUserController {

    public void assignAssetToUser(ID assetId, ID userId){

    }

    public void updateAssetToUser(ID assetToUserId, ID assetId, ID userId){

    }

    public void removeAssetToUser(ID assetToUserId){

    }

    public List<A18_DTO.AssetStatus> getAssetStatuses(){

        //temporarily
        return NULL;

    }

    public List<A18_DTO.AssetUser> searchAssetUsers(String searchPhrase, String status){

        //temporarily
        return NULL;

    }

}